"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { createStockTransfer } from "@/app/actions/transfers";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Option = { id: string; name: string; branchId?: string };
type Variant = { id: string; label: string };
type Row = { variantId: string; quantity: string };
export function TransferForm({ branches, warehouses, variants }: { branches: Option[]; warehouses: Option[]; variants: Variant[] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [error, setError] = useState(""); const [rows, setRows] = useState<Row[]>([{ variantId: "", quantity: "1" }]);
  function submit(formData: FormData) { setError(""); const payload = { fromBranchId: String(formData.get("fromBranchId") || ""), toBranchId: String(formData.get("toBranchId") || ""), fromWarehouseId: String(formData.get("fromWarehouseId") || ""), toWarehouseId: String(formData.get("toWarehouseId") || ""), items: rows }; startTransition(async () => { const result = await createStockTransfer(payload); if (!result.ok) return setError(result.error); router.refresh(); }); }
  return <form action={submit} className="space-y-4">{error && <p className="text-[13px] text-danger">{error}</p>}<div className="grid gap-2 sm:grid-cols-4"><select name="fromBranchId" required className="h-9 rounded border border-border-strong bg-surface px-2 text-sm"><option value="">From branch...</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="fromWarehouseId" required className="h-9 rounded border border-border-strong bg-surface px-2 text-sm"><option value="">From warehouse...</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="toBranchId" required className="h-9 rounded border border-border-strong bg-surface px-2 text-sm"><option value="">To branch...</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="toWarehouseId" required className="h-9 rounded border border-border-strong bg-surface px-2 text-sm"><option value="">To warehouse...</option>{warehouses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>{rows.map((row, index) => <div key={index} className="grid gap-2 sm:grid-cols-[1fr_140px_auto]"><select aria-label="Transfer product" value={row.variantId} onChange={(event) => setRows((current) => current.map((item, rowIndex) => rowIndex === index ? { ...item, variantId: event.target.value } : item))} className="h-9 rounded border border-border-strong bg-surface px-2 text-sm"><option value="">Product...</option>{variants.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><Input aria-label="Transfer quantity" type="number" min="0.001" step="0.001" value={row.quantity} onChange={(event) => setRows((current) => current.map((item, rowIndex) => rowIndex === index ? { ...item, quantity: event.target.value } : item))} /><Button type="button" variant="secondary" onClick={() => setRows((current) => current.length === 1 ? current : current.filter((_, rowIndex) => rowIndex !== index))}>Remove</Button></div>)}<Button type="button" variant="secondary" onClick={() => setRows((current) => [...current, { variantId: "", quantity: "1" }])}>Add item</Button><Button type="submit" disabled={pending}>{pending ? "Transferring..." : "Complete transfer"}</Button></form>;
}
